version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/soshi.db
      - MIGRATIONS_PATH=file:///app/pkg/db/migrations/sqlite
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
